---
# tasks file for demo-poc
- name: copy jar file
  ansible.builtin.copy:
    src: /var/lib/jenkins/workspace/demo-poc-pipeline/build/libs/
    dest: /opt/demo.jar

- name: starting the spring service
  shell: systemctl start demo.service

