name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      password:
        required: true
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: push image to docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: shaan168/aravind
        tags: gradle_demo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
